name: Server Control Panel
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação a ser executada (start-server)'
        required: true
        default: 'start-server'

jobs:
  control-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Start Codespace
        if: github.event.inputs.action == 'start-server'
        env:
          GITHUB_TOKEN: ${{ secrets.CODESPACE_CONTROL_TOKEN }}
          CODESPACE_NAME: "fictional-succotash-jjwrw96vjprrh5vrj" # COLOQUE O NOME DO SEU CODESPACE AQUI
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/user/codespaces/$CODESPACE_NAME/start"
