name: Server Control Panel
on:
  repository_dispatch:
    types: [start-server]
jobs:
  control-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Start Codespace
        if: github.event.action == 'start-server'
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CODESPACE_CONTROL_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/user/codespaces/${{ github.event.client_payload.codespace }}/start"
